// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "getcontactdetails",
    id: "55b0718f-7109-422a-8366-5d259e696cb4",
    method: "GET",
    address: "https://test.k6.io/contacts.php"
  });

  postman[Request]({
    name: "newslisting",
    id: "b862fe8d-ed11-483d-bc87-74b219fb0c4a",
    method: "GET",
    address: "https://test.k6.io/news.php"
  });

  postman[Request]({
    name: "retrievemessage",
    id: "f8392702-ba41-441f-be40-a501cf7a52ed",
    method: "GET",
    address: "https://test.k6.io/my_messages.php"
  });
}
